#!/bin/sh
set -e

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/e2fsck /sbin
copy_exec /sbin/fsck.ext4 /sbin
copy_exec /sbin/blkid /sbin
copy_exec /sbin/cryptsetup /sbin

# plymouth は無い環境もあるので、あれば取り込む
if [ -x /bin/plymouth ]; then
    copy_exec /bin/plymouth /bin
elif [ -x /usr/bin/plymouth ]; then
    copy_exec /usr/bin/plymouth /usr/bin
fi

exit 0
